config/routes.rb
Rails.application.routes.draw do
  get 'destination', controller: :travel, action: :destination, alias: 'destination'

  get 'tips', controller: :travel, action: :tips, alias: 'tips'

  get 'tops', controller: :travel, action: :tops, alias: 'tops'

  get 'contact', controller: :travel, action: :contact, alias: 'contact'

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/travel_controller.rb
class TravelController < ApplicationController
	layout 'travel'
  def destination
  end

  def tips
  end

  def tops
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/travel_helper.rb
module TravelHelper
end

app/views/home/index.html.erb
<h1>Bienvenido a Amaizing Travel</h1>
<h3>35 años con las mejores tarifas siempre!</h3>
<p>Nos encargamos de ofrecerte diariamente los mejores precios en pasajes a&eacute;reos, hoteles, paquetes tur&iacute;sticos, alquiler de autos, cruceros y m&aacute;s.</p>

<p>Gracias por visitar nuestro site, Amaizing Travel, es una agencia líder en el área de negocios del turismo en la Costa Este de los Estados Unidos de Norte América, contamos con atención especializada en los más diversos productos del rubro, como asesoría y venta de pasajes aéreos nacionales e internacionales, paquetes turísticos, cruceros marítimos y arriendo de autos.</p>

<p>Fuimos los pioneros en la implementación de estrategias de comercio electrónico en el año 2000, mejoramos constantemente nuestro portal y en consecuencia le damos a UD. los mejores precios y/o tarifas, para Norte, Centro y Sudamérica, Europa, Asia y Medio Oriente.</p>

app/views/layouts/_menu.html.erb
<ul class="nav navbar-nav">
	<li><%= link_to 'Destinos', destination_path %></li>
	<li><%= link_to 'Tips', tips_path %></li>
	<li><%= link_to 'Tops', tops_path %></li>
	<li><%= link_to 'Contactenos', contact_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  	<a class="navbar-brand navbar-light " href=<%= root_path %>>Amaizing Travel</a>
  	
    <%= render partial: 'layouts/menu' %>
  	<!-- <#%= yield %> -->
  	
  	<div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->
    </div> <!-- /container -->
  </div> <!-- /container -->

</body>
</html>

app/views/layouts/travel.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Travelapp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="navbar navbar-inverse navbar-static-top">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= root_path %>>Amaizing Travel</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <%= render partial: 'layouts/menu' %>
        </div>
      </div>
    </div> <!-- /container -->

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield :head %>
          <%= yield :intro %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p></p>
        <p>&copy; Giol Company 2016. Todos los derechos reservados</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/travel/_map.html.erb
<iframe
  width="400"
  height="350"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA8gEKnNs6pPNLTD5OBogTBnPS6_0iBc6I
    &q=Universidad%20Peruana%20de%20Ciencias%20Aplicadas" allowfullscreen>
</iframe>

app/views/travel/contact.html.erb
<%= content_for :head do %>
	<div class="col-lg-9">
		<h3 class="text-primary"><strong>Cont&aacute;ctenos</strong></h3>
	</div>
<% end %>

<div class="col-lg-9">
	<div class="col-lg-6">
		<div class="panel panel-info">
	  		<div class="panel-heading">
	  			<%= form_tag("/get", method: "get") do %>
					<%= label_tag(:name, "Name:") %>
					<div> <%= text_field_tag(:q) %></div>
				
					<%= label_tag(:mail, "E-Mail:") %>
					<div> <%= text_field_tag(:q) %></div>
					
					<%= label_tag(:comment, "Message:") %>
					<div> <%= text_field_tag(:q) %></div>
					<p></p>
					<div><%= submit_tag("Enviar") %></div>	
				<% end %>
		
	  		</div>
		</div>  	
	</div>
	<div class="col-lg-3">
		<div id="maps">
	    	<%= render 'map' %> 
		</div>
	</div>
	
	
</div>

app/views/travel/destination.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
		<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
		<li data-target="#carousel-example-generic" data-slide-to="1"></li>
		<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		<li data-target="#carousel-example-generic" data-slide-to="3"></li>
		<li data-target="#carousel-example-generic" data-slide-to="4"></li>
	</ol>

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item active">
			<%= image_tag "arequipa.jpg", html: {alt: "arequipa"} %>
      		<div class="carousel-caption">
      			<h2>5 planes en Arequipa y sus alrededores</h2>
      			<div class="carousel-caption-opacity">
					<p>Los encantos del sur de Per&uacute; son para muchos insospechables, ya que conjugan historia, arqueolog&iacute;a, aventura y naturaleza de una manera casi perfecta. Viajar a Arequipa es ideal para cualquier tipo de turista, ya que en la parte urbana cuenta…</p>
					<a href="#" class="btn btn-sm btn-primary">Learn More</a>
				</div>
			</div>
		</div>

		<div class="item">
      		<%= image_tag "playas.jpg", html: {alt: "playas"} %>
			<div class="carousel-caption">
				<h2>Tips de viaje para visitar Jamaica</h2>
				<div class="carousel-caption-opacity">	
					<p>Sin duda Jamaica nos trae a la mente las canciones de Bob Marley, icono m&aacute;ximo del reaggue. Sin embargo, esta ex&oacute;tica isla es más que música y deportes de aventura. Es un m&aacute;gico lugar que mezcla naturaleza, m&uacute;sica y arte…</p>
					<a href="#" class="btn btn-sm btn-primary">Learn More</a>
				</div>
			</div>
		</div>

		<div class="item">
      		<%= image_tag "colombia.jpg", html: {alt: "colombia"} %>
			<div class="carousel-caption">
				<h2>Ocho bellos lugares para conocer en Colombia y no perderte de nada</h2>
				<div class="carousel-caption-opacity">	
					<p>Colombia es uno de los destinos m&aacute;s visitados en Sudam&eacute;rica y ello por simples razones. Es un pa&iacute;s muy rico en cultura, gastronom&iacute;a y bellos paisajes. Es un destino ideal para conocer durante vacaciones, pues su gente es c&aacute;lida y…</p>
					<a href="#" class="btn btn-sm btn-primary">Learn More</a>
				</div>
			</div>
		</div>

		<div class="item">
			<%= image_tag "glaciares.jpg", html: {alt: "glaciares"} %>
      		<div class="carousel-caption">
				<h2>10 lugares que no debes perderte si visitas Argentina</h2>
				<div class="carousel-caption-opacity">	
					<p>Argentina es uno de los destinos tur&iacute;sticos m&aacute;s visitados en Am&eacute;rica del Sur y no es por simple capricho, pues es un pa&iacute;s que tiene mucho por ofrecer. Desde bellos escenarios naturales, lagos, montañas y nevados, hasta hermosas playas y una gastronomía…</p>
					<a href="#" class="btn btn-sm btn-primary">Learn More</a>
				</div>
			</div>
		</div>
		
		<div class="item">
			<%= image_tag "panama.jpg", html: {alt: "panama"} %>
      		<div class="carousel-caption">
				<h2>Panam&aacute; un destino de playas, compras y mucho m&aacute;s</h2>
				<div class="carousel-caption-opacity">	
					<p>Panam&aacute; es uno de los destinos turísticos m&aacute;s visitados en Centroam&eacute;rica, pues ofrece una gran variedad de actividades tur&iacute;sticas. En esta ciudad puedes encontrar playas paradis&iacute;acas, ir de compras en los centros comerciales m&aacute;s grandes del mundo y hasta probar…</p>
					<a href="#" class="btn btn-sm btn-primary">Learn More</a>
				</div>
			</div>
		</div>
	</div>	
	
	<!-- Controls -->
	<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    	<span class="sr-only">Previous</span>
  	</a>

  	<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    	<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    	<span class="sr-only">Next</span>
  	</a>
</div>

app/views/travel/tips.html.erb
<%= content_for :head do %>
	<div class="col-lg-9">
		<h1 class="text-primary">
			<strong>6 razones para pasar tus vacaciones en las Bahamas</strong>
		</h1>
	</div>
<% end %>

<%= content_for :intro do %>
	<div class="col-lg-9">
		<p>¿Quieres vivir unas vacaciones inolvidables en el Caribe? Aquí te dejamos 6 buenas razones por las cuales debes viajar a Bahamas.</p>
	</div>
<% end %>

<div class="col-lg-9">
	
	<%= image_tag "bahamas1.jpg", class: "img-small-view", html: {alt: "bahamas1"} %>
	<p></p>
	<p class="text-justify">Si quieres desconectarte de la ciudad y pasar un momento de ensueño en un paraíso tropical, no puedes dejar de viajar a Bahamas. Este famoso archipiélago es visitado todos los años por miles de turistas, quienes quedan fascinados por sus bellos paisajes naturales. Si estás buscando un destino caribeño para pasar las vacaciones, no dejes de leer estos 6 motivos por los cuales debes visitar Bahamas.</p>

	<h3 class="text-primary"><strong> El legado colonial de Nasáu</strong></h3>
	<p class="text-justify">CNasáu fue originalmente bautizada Charles Town, en honor al rey Carlos III de Inglaterra. Sin embargo, debido a que los piratas la utilizaban como escondite, fue destruida y reconstruida en numerosas ocasiones. Debido a la ocupación británica y española, Nasáu cuenta con bellos edificios que son el legado de la arquitectura colonial. Destacan las villas victorianas, las iglesias y fortalezas.</p>

	<h3 class="text-primary"><strong>Sus playas</strong> </h3>
	<p class="text-justify">En Bahamas pueden encontrarse algunas de las playas más bellas de la región del Caribe. Debido a sus aguas cristalinas, son perfectas para la práctica del buceo.</p>
	
	<%= image_tag "bahamas2.jpg", class: "img-small-view", html: {alt: "bahamas2"} %>

	<h3 class="text-primary"><strong>Pesca</strong> </h3>
	<p class="text-justify">Bahamas es hogar de habilidosos pescadores que todos los años sorprenden a los turistas en los torneos de pesca. Además, la isla de Andros es considerada la capital mundial de la pesca del pez ratón.</p>
	
	<%= image_tag "bahamas3.jpg",  class: "img-small-view", html: {alt: "bahamas3"}%>
</div>

app/views/travel/tops.html.erb
<%= content_for :head do %>
	<div class="col-lg-12">
		<h1 class="text-primary">
			<strong>Los 4 mejores destinos del mundo para ir de compras.</strong>
		</h1>
	</div>
<% end %>

<%= content_for :intro do %>
	<div class="col-lg-12">
		<p>¿Quieres ir de compras? Conoce cuáles son los mejores destinos para adquirir productos de moda y tecnología.</p> 
		<p>No hay nada más reconfortante que salir de viaje con las maletas vacías y traerlas llenas. Si tu objetivo es conseguir los últimos productos de moda y tecnología, te recomendamos visitar estos destinos.</p>
	</div>
<% end %>

<div class="col-lg-12">	
	<div class="col-md-6">
		<%= image_tag "york.jpg", class: "img-col6-view", html: {alt: "york"} %>	
		<h3 class="text-danger"><strong>Nueva York</strong></h3>
		<p class="text-justify">Si estás buscando marcas de diseñadores, Nueva York es el lugar al que debes ir. En la ciudad de los rascacielos puedes encontrar productos de Versace, Calvin Klein o Marc Jacobs con descuentos de hasta el 70%.</p>
	</div>
	<div class="col-md-6">
		<%= image_tag "madrid.jpg", class: "img-col6-view", html: {alt: "madrid"} %>
		<h3 class="text-danger"><strong>Madrid</strong></h3>
		<p class="text-justify">En Madrid puedes encontrar artículos de lujo a muy buen precio. Algunos de los mejores productos que puedes comprar son capas de lana y terciopelo de algodón, abanicos, paraguas, peinetas ornamentales y hermosas castañuelas. </p>
	</div>
	<div class="col-md-6">
		<%= image_tag "paris.jpg", class: "img-col6-view", html: {alt: "paris"} %>
		<h3 class="text-danger"><strong>Paris</strong></h3>
		<p class="text-justify">En París se respira arte en cada calle y, por supuesto, cada tienda. Puedes encontrar hermosos productos de decoración, moda de alta costura, mueblería fina y mucho más.</p>
	</div>
	<div class="col-md-6">
		<%= image_tag "londres.jpg", class: "img-col6-view", html: {alt: "londres"} %>
		<h3 class="text-danger"><strong>Londres</strong></h3>
		<p class="text-justify">Según el Globe Shopper Index, Londres es una de las mejores ciudades europeas para ir de compras. Aunque los precios no son tan bajos como en otros países, si cuenta con una gran cantidad de tiendas de mucha calidad.</p>
	</div>
</div>